name: procis3d
description: A 3D teaching aid for the benefit of teachers to teach otherwise difficult concepts and facilitate better learning and retention by the students. This essentially supports visualization in many courses in electronics.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_advanced_drawer: ^1.2.1
  url_launcher: ^6.0.7
  flutter_cube: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/
    - assets/objects/

  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
